version: '3.9'

services:
  db1:
    image: postgres:latest
    container_name: db1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db1_data:/var/lib/postgresql/data
    networks:
      - my-network
    
  spark-master:
    image: bitnami/spark:3.3.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - C:/project/data:/data  
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - my-network

  spark-worker-1:
    image: bitnami/spark:3.3.1
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
    volumes:
      - C:/project/data:/data  
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - my-network

  pyspark:
    image: jupyter/pyspark-notebook:spark-3.3.1
    container_name: pyspark
    user: root
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_LOCAL_IP=pyspark
      - SPARK_LOCAL_HOSTNAME=pyspark
    volumes:
      - C:/project/data:/data  
    ports:
      - "8888:8888"
    depends_on:
      - spark-master
      - spark-worker-1  
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "15432:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db1_data:
