version: 1
default_environment: dev
project_id: 32eca16d-9a3e-4798-a158-b9793555307b
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    config:
        database: Amazon
        host: localhost
        port: 5433
        user: postgres
        filter_schemas: ["public"]
        default_replication_method: FULL_TABLE
  loaders:
  - name: target-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-csv.git
    config:
        destination_path: ../data/not-process
jobs:
  - name: extract-data
    tasks:
    - tap-postgres target-csv
schedules:
  - name: extract
    interval: '@daily'
    job: extract-data

