version: 1
default_environment: dev
project_id: a0932c12-9783-4fd5-88f6-6cb529e2ef20
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    config:
      database: Amazon
      host: localhost
      user: postgres
      filter_schemas:
      - public
      default_replication_method: FULL_TABLE
      port: 5433
  loaders:
  - name: target-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-csv.git
    config:
      destination_path: ../data

  utilities: 
  - name: organize-files
    namespace: organize-files
    commands: 
      organize_files:
        args: python/organize_files.py
        executable: python
jobs:
- name: extract
  tasks:
  - tap-postgres target-csv
  - organize-files:organize_files
